### ISSUE TITLE
Run Time error

### ISSUE THREAD

**Issue by vikky49** [mallowigi/mtslack#47]
When I try to install these either by building or by globally installing I was getting the following error

`current theme is now Material Oceanic
(node:55261) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token = in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.parse (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/rc/index.js:43:36)
    at module.exports (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/registry-url/index.js:3:24)
    at module.exports (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/package-json/index.js:22:12)
    at module.exports (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/latest-version/index.js:5:2)
    at UpdateNotifier.checkNpm (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/update-notifier/index.js:71:2)
    at UpdateNotifier.check (/Users/pchandra/OpenSourceProjects/slack-themes/node_modules/update-notifier/index.js:45:15)
(node:55261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:55261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mallowigi** [comment]
Is this your first install?

**Comment by vikky49** [comment]
yeah

**Comment by mallowigi** [comment]
Windows? I'm sorry but I'm out of windows machines at the moment. Please try to reinstall Slack from scratch and try again, if it doesnt help please be patient.

**Comment by mallowigi** [comment]
Try to reinstall slack and launch mtslack again.
