### ISSUE TITLE
mtslack Apply Theme permission denied

### ISSUE THREAD

**Issue by buzzin0609** [mallowigi/mtslack#51]
**Describe the bug**
Installed no problem, but running the `mtslack` command and choosing "Apply Theme" produces `Error: EACCES: permission denied` error

**To Reproduce**
1. npm install -g mtslack
2. run `mtslack`, choose `Apply Theme`
3. See error

**Expected behavior**
Process should continue without error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Node version 12.16.2

**Additional context**
The error stacktrace:

```
 UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/usr/lib/slack/resources/app.asar' -> '/usr/lib/slack/resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1808:3)
    at Object.exports.apply (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/lib/command.js:166:6)
    at Object.exports.selectTheme (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/lib/command.js:204:8)
    at Object.exports.change (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/lib/command.js:195:8)
    at exports.execute (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/lib/command.js:210:12)
    at run (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/main.js:27:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AutoUpdate.<anonymous> (/home/will/.nvm/versions/node/v12.16.2/lib/node_modules/mtslack/main.js:55:7)
(node:26553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mallowigi** [comment]
You're right. I need to write on the README that you need to run the command in sudo to work.
