### ISSUE TITLE
Unhandled promise rejection on macOS with Slack 4.12

### ISSUE THREAD

**Issue by PSalant726** [mallowigi/mtslack#54]
**Describe the bug**
Unhandled promise rejection error when running `sudo mtslack` on macOS 10.15.7 after updating to Slack 4.12

**To Reproduce**
1. Update to Slack v4.12 via the mac app store, on macOS v10.15.7
2. Run `sudo mtslack` (v15.0.0) from a command line
3. Select "Apply Tweaks"
4. Observe the unhandled promise rejection error

**Expected behavior**
The `sudo mtslack` command runs successfully and exits without any errors.

**Screenshots**
Full `mtslack` output, including the reported error:
```
Checking for updates...
Finished checking for updates!
                               d8b                   d8b
                 d8P           88P                   ?88
              d888888P        d88                     88b
  88bd8b,d88b   ?88'   .d888b,888   d888b8b   d8888b  888  d88'
  88P'`?8P'?8b  88P    ?8b,   ?88  d8P' ?88  d8P' `P  888bd8P'
 d88  d88  88P  88b      `?8b  88b 88b  ,88b 88b     d88888b
d88' d88'  88b  `?8b  `?888P'   88b`?88P'`88b`?888P'd88' `?88b,



version 15.0.0 by @mallowigi
Welcome to the mtslack CLI!

? Please select an command Apply tweaks
Removing tweaks...

Successfully removed!

Adding Tweaks Code to Slack...

(node:7833) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Applications/Slack.app/Contents/Resources/app.asar.unpacked/dist/preload.bundle.js'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at Object.appendFileSync (fs.js:1506:6)
    at Object.exports.apply (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/lib/command.js:176:6)
    at Object.exports.selectTheme (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/lib/command.js:210:8)
    at Object.exports.change (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/lib/command.js:201:8)
    at exports.execute (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/lib/command.js:216:12)
    at run (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/main.js:32:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AutoUpdate.<anonymous> (/Users/{{ user directory }}/.volta/tools/image/packages/mtslack/lib/node_modules/mtslack/main.js:60:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Firefox
 - Version: mtslack 15.0.0

**Comment by mallowigi** [comment]
Awww... they changed the way it loads... Hope it's not lost...

**Comment by nickjannes101** [comment]
Same error here, I'm on MacOS 11.1, Slack version 4.12 and mtslack version 15.0.0

**Comment by nickjmv** [comment]
Same error here, I'm on MacOS 11.1, Slack version 4.12 and mtslack version 15.0.0

**Comment by mallowigi** [comment]
Updated. I haven't tested on all platforms, please tell me if there is still an issue.

**Comment by PSalant726** [comment]
I opened #55 to address a bug with the autoupdate feature, but after reinstalling with `npm install -g mtslack`, I can confirm that this issue is resolved. Thanks for the quick turnaround!
