### ISSUE TITLE
Unable to run - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by intemperie** [mallowigi/mtslack#64]
Hi! It's the first time I install this, and unfortunately, I'm not able to run it. I'm getting the following error:

- macOS 11.2.1
- Slack Version 4.13.0

```
/usr/local/lib/node_modules/mtslack/node_modules/chalk/source/index.js:106
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mtslack/main.js:2:15)
```

I tried uninstalling and reinstalling Slack, and the same thing happens. Any ideas?

Thanks!

**Comment by mallowigi** [comment]
Hmmm... what version of nodejs do you have?

**Comment by intemperie** [comment]
Ah, that was it. I upgraded node and now it works. Thanks!!
