### ISSUE TITLE
Issue since last Slack update

### ISSUE THREAD

**Issue by olivierpilotte** [mallowigi/mtslack#74]
**Describe the bug**
Running `Apply tweaks` doesn't work since lastest update.

**To Reproduce**
1. `npm run apply`
2. Apply tweaks

**Expected behavior**
Tweaks are applied and `npm run apply` exits successfully

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro)
 - Version: 4.14.0 64-bit (3b9cbf8039ba49e7b6a5f03e8f467cf04d3abe31@1623908846)

**Additional context**
Slack trace:

```
(node:921136) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/lib/slack/resources/app.asar.unpacked/node_modules/@nodert-win10-au/windows.applicationmodel/bin/linux-x64-87/windows.applicationmodel.node'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.module.exports.readFileSync (/home/opilotte/dev/github/mtslack/node_modules/@mallowigi/asar/lib/disk.js:110:17)
    at Object.module.exports.extractAll (/home/opilotte/dev/github/mtslack/node_modules/@mallowigi/asar/lib/asar.js:200:28)
    at Object.exports.apply (/home/opilotte/dev/github/mtslack/lib/command.js:205:8)
    at Timeout._onTimeout (/home/opilotte/dev/github/mtslack/lib/command.js:253:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:921136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:921136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mallowigi** [comment]
man linux is a pain...

**Comment by olivierpilotte** [comment]
I disagree. Slack is a pain.

**Comment by shalaga44** [comment]
I have the same issue using snap
```
/ Processing...(node:9301) UnhandledPromiseRejectionWarning: Error: EROFS: read-only file system, copyfile '/snap/slack/current/usr/lib/slack/resources/app.asar' -> '/snap/slack/current/usr/lib/slack/resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1728:3)
    at Object.exports.apply (/usr/local/lib/node_modules/mtslack/lib/command.js:203:6)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/mtslack/lib/command.js:253:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:9301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9301) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by jsievenpiper** [comment]
I think this is the same as #83. Seems relatively easy to work around, but I don't have any electron experience, so I couldn't tell you more than that unfortunately. Hope that helps!
